-- Forward-only: historical manual orders are preserved and excluded from Vibe activation.
SET LOCAL search_path=airtime,public;
ALTER TABLE ad_campaigns ADD COLUMN product_version smallint NOT NULL DEFAULT 1;
ALTER TABLE ad_campaigns ALTER COLUMN product_version SET DEFAULT 2;
ALTER TABLE ad_campaigns DROP CONSTRAINT ad_campaigns_status_check;
ALTER TABLE ad_campaigns ADD CONSTRAINT ad_campaigns_status_check CHECK(status IN ('DRAFT','CREATIVE_UPLOADING','SUBMITTED_FOR_REVIEW','CREATIVE_PENDING','CHANGES_REQUESTED','CREATIVE_REJECTED','APPROVED_AWAITING_PAYMENT','QUOTE_ACTIVE','PAYMENT_VERIFYING','PAID','ACTIVATING','UPCOMING','DELIVERING','PAUSED','COMPLETED','ACTIVATION_FAILED','REFUND_REVIEW','REFUNDED','AWAITING_PAYMENT','COMPLIANCE_REVIEW','APPROVED','SCHEDULING','SCHEDULED','LIVE','REJECTED','REFUND_PENDING'));
ALTER TABLE ad_campaigns ADD CONSTRAINT fixed_v1_media CHECK(product_version=1 OR media_budget_cents=5000);
ALTER TABLE campaign_invoices ADD COLUMN product_version smallint NOT NULL DEFAULT 1;
ALTER TABLE campaign_invoices ALTER COLUMN product_version SET DEFAULT 2;
ALTER TABLE campaign_invoices ADD COLUMN payment_reference uuid NOT NULL DEFAULT gen_random_uuid();
CREATE UNIQUE INDEX invoice_payment_reference ON campaign_invoices(payment_reference);
CREATE UNIQUE INDEX one_paid_order ON campaign_invoices(campaign_id) WHERE status='PAID';
ALTER TABLE campaign_invoices ADD CONSTRAINT fixed_v1_invoice CHECK(product_version=1 OR (media_budget_cents=5000 AND platform_fee_cents=1000 AND total_usd_cents=6000 AND expires_at<=created_at+interval '5 minutes'));
-- Unpaid old quotes must never enter the new fixed-product workflow.
UPDATE campaign_invoices SET status='CANCELLED' WHERE product_version=1 AND status='OPEN' AND prepared_message IS NULL;
CREATE TABLE vibe_advertisers(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES platform_users(id),mint text NOT NULL REFERENCES platform_coins(mint),account_id bigint NOT NULL,external_id uuid UNIQUE,name text NOT NULL,website text NOT NULL,status text NOT NULL DEFAULT 'NOT_EXPOSED',last_synced_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(user_id,mint),UNIQUE(id,user_id));
CREATE TABLE vibe_campaigns(campaign_id uuid PRIMARY KEY,user_id uuid NOT NULL,advertiser_id uuid NOT NULL,account_id bigint NOT NULL,external_id uuid UNIQUE,name text NOT NULL,provider_status text,delivery_status text,last_error text,last_synced_at timestamptz,report_id uuid,report_requested_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),FOREIGN KEY(campaign_id,user_id) REFERENCES ad_campaigns(id,user_id),FOREIGN KEY(advertiser_id,user_id) REFERENCES vibe_advertisers(id,user_id));
CREATE TABLE vibe_creatives(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),campaign_id uuid NOT NULL,user_id uuid NOT NULL,creative_id uuid NOT NULL REFERENCES campaign_creatives(id),external_id uuid UNIQUE,upload_id uuid,name text NOT NULL,approval_status text CHECK(approval_status IN ('PROCESSING','PENDING_REVIEW','AUTHORIZED','BLOCKED')),approval_details text,last_synced_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),UNIQUE(campaign_id,creative_id),FOREIGN KEY(campaign_id,user_id) REFERENCES ad_campaigns(id,user_id));
CREATE TABLE vibe_strategies(campaign_id uuid PRIMARY KEY REFERENCES vibe_campaigns(campaign_id),external_id uuid UNIQUE,name text NOT NULL,budget_cents bigint NOT NULL DEFAULT 5000 CHECK(budget_cents=5000),budget_type text NOT NULL DEFAULT 'GLOBAL' CHECK(budget_type='GLOBAL'),targeting jsonb NOT NULL,starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL CHECK(ends_at>starts_at),active boolean NOT NULL DEFAULT false,provider_state text,last_synced_at timestamptz);
CREATE TABLE vibe_operations(operation_key text PRIMARY KEY,campaign_id uuid NOT NULL REFERENCES ad_campaigns(id),kind text NOT NULL,request_payload jsonb NOT NULL,request_hash text NOT NULL,status text NOT NULL DEFAULT 'READY' CHECK(status IN ('READY','IN_FLIGHT','UNKNOWN','COMPLETE','FAILED')),external_id uuid,response_payload jsonb,error text,retry_count integer NOT NULL DEFAULT 0 CHECK(retry_count>=0),next_attempt_at timestamptz NOT NULL DEFAULT now(),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vibe_campaign_metrics(campaign_id uuid PRIMARY KEY REFERENCES vibe_campaigns(campaign_id),spend_microusd bigint CHECK(spend_microusd>=0),impressions bigint CHECK(impressions>=0),completed_views bigint CHECK(completed_views>=0),households bigint CHECK(households>=0),view_through_rate text,cpm text,frequency text,starts_at timestamptz,ends_at timestamptz,last_synced_at timestamptz NOT NULL,raw_summary jsonb NOT NULL);
CREATE TABLE vibe_channel_reports(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),campaign_id uuid NOT NULL REFERENCES vibe_campaigns(campaign_id),dimension text NOT NULL,label text NOT NULL,metrics jsonb NOT NULL,synced_at timestamptz NOT NULL,UNIQUE(campaign_id,dimension,label));
CREATE TABLE campaign_settlements(invoice_id uuid PRIMARY KEY REFERENCES campaign_invoices(id),campaign_id uuid NOT NULL REFERENCES ad_campaigns(id),customer_lamports bigint NOT NULL CHECK(customer_lamports>0),media_cents bigint NOT NULL CHECK(media_cents=5000),service_fee_cents bigint NOT NULL CHECK(service_fee_cents=1000),status text NOT NULL DEFAULT 'PENDING_CONVERSION' CHECK(status IN ('PENDING_CONVERSION','CONVERTED','VIBE_FUNDED','RECONCILED','FAILED')),conversion_reference text,vibe_spend_microusd bigint,reason text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vibe_reconciliation_runs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),started_at timestamptz NOT NULL DEFAULT now(),completed_at timestamptz,status text NOT NULL DEFAULT 'RUNNING',processed integer NOT NULL DEFAULT 0,error text);
CREATE TABLE vibe_alerts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),dedupe_key text NOT NULL UNIQUE,campaign_id uuid REFERENCES ad_campaigns(id),kind text NOT NULL,severity text NOT NULL CHECK(severity IN ('INFO','WARNING','ERROR')),message text NOT NULL,resolved_at timestamptz,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE vibe_account_snapshots(account_id bigint PRIMARY KEY,balance_cents bigint,currency text,last_synced_at timestamptz,last_error text,raw_status jsonb NOT NULL DEFAULT '{}');
UPDATE settings SET config=config||'{"vibeActivationEnabled":false}'::jsonb WHERE id=true;
CREATE INDEX vibe_pending_sync ON vibe_campaigns(last_synced_at);
CREATE INDEX vibe_retry_jobs ON vibe_operations(status,next_attempt_at);
CREATE INDEX vibe_open_alerts ON vibe_alerts(created_at DESC) WHERE resolved_at IS NULL;
ALTER TABLE campaign_invoices ADD COLUMN approval_evidence jsonb NOT NULL DEFAULT '{}';
CREATE FUNCTION fixed_product_payment_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE i campaign_invoices;c ad_campaigns;BEGIN SELECT * INTO i FROM campaign_invoices WHERE id=NEW.invoice_id; SELECT * INTO c FROM ad_campaigns WHERE id=i.campaign_id; IF i.product_version=2 AND (c.product_version<>2 OR i.approval_evidence->>'status' IS DISTINCT FROM 'AUTHORIZED') THEN RAISE EXCEPTION 'Approved fixed-product quote required';END IF;RETURN NEW;END $$;
CREATE TRIGGER require_approved_payment BEFORE INSERT ON campaign_payments FOR EACH ROW EXECUTE FUNCTION fixed_product_payment_guard();
CREATE FUNCTION immutable_payment_reference() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.payment_reference<>OLD.payment_reference OR NEW.product_version<>OLD.product_version OR NEW.approval_evidence<>OLD.approval_evidence THEN RAISE EXCEPTION 'Payment reference is immutable';END IF;RETURN NEW;END $$;
CREATE TRIGGER fixed_quote_reference BEFORE UPDATE ON campaign_invoices FOR EACH ROW EXECUTE FUNCTION immutable_payment_reference();
DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['vibe_advertisers','vibe_campaigns','vibe_creatives','vibe_strategies','vibe_operations','vibe_campaign_metrics','vibe_channel_reports','campaign_settlements','vibe_reconciliation_runs','vibe_alerts','vibe_account_snapshots'] LOOP EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);EXECUTE format('REVOKE ALL ON %I FROM PUBLIC',t);END LOOP;END $$;

CREATE FUNCTION approved_quote_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE c ad_campaigns; BEGIN IF NEW.product_version=2 THEN SELECT * INTO c FROM ad_campaigns WHERE id=NEW.campaign_id;IF c.product_version<>2 OR c.status NOT IN ('APPROVED_AWAITING_PAYMENT','QUOTE_ACTIVE') OR NEW.approval_evidence->>'status' IS DISTINCT FROM 'AUTHORIZED' OR NOT EXISTS(SELECT 1 FROM vibe_creatives vc WHERE vc.campaign_id=c.id AND vc.creative_id=(c.brief->>'creativeId')::uuid AND vc.external_id::text=NEW.approval_evidence->>'vibe_creative_id' AND vc.approval_status='AUTHORIZED') THEN RAISE EXCEPTION 'Verified approved creative required for quote';END IF;END IF;RETURN NEW;END $$;
CREATE TRIGGER approved_fixed_quote BEFORE INSERT ON campaign_invoices FOR EACH ROW EXECUTE FUNCTION approved_quote_guard();

CREATE FUNCTION fixed_campaign_version_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.product_version<>OLD.product_version THEN RAISE EXCEPTION 'Product version is immutable'; END IF;RETURN NEW;END $$;
CREATE TRIGGER immutable_product_version BEFORE UPDATE ON ad_campaigns FOR EACH ROW EXECUTE FUNCTION fixed_campaign_version_guard();
ALTER TABLE vibe_campaigns ADD COLUMN retry_count integer NOT NULL DEFAULT 0 CHECK(retry_count BETWEEN 0 AND 12);
ALTER TABLE vibe_campaigns ADD COLUMN next_attempt_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE vibe_campaigns ADD COLUMN breakdown_report_id uuid;
ALTER TABLE vibe_campaigns ADD COLUMN breakdown_dimension text NOT NULL DEFAULT 'channel_name' CHECK(breakdown_dimension IN ('channel_name','geo_region'));

ALTER TABLE vibe_strategies ADD COLUMN activation_starts_at timestamptz;
ALTER TABLE vibe_strategies ADD COLUMN activation_ends_at timestamptz;
ALTER TABLE vibe_strategies ADD CONSTRAINT activation_finite_window CHECK(activation_ends_at IS NULL OR activation_ends_at>activation_starts_at);
